{% set name = "local-attention" %}
{% set version = "1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 94e48fec748e96fa81ac6c3e27a357950eaab22cd8f69a10c50b23d6eec8f09c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >={{ python_min }}
    - einops >=0.8.0
    - hyper-connections >=0.1.8
    - pytorch

test:
  imports:
    - local_attention
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/local-attention
  summary: Local attention, window with lookback, for language modeling
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
