{% set name = "local-attention" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/local-attention-{{ version }}.tar.gz
  sha256: e6d27a0af622caf3b05cc1d644f16c3f65b0893d299e3100d0785b528985317c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch

test:
  imports:
    - local_attention
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lucidrains/local-attention
  summary: Local windowed attention, for language modeling
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
