{% set name = "local-attention" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/local-attention-{{ version }}.tar.gz
  sha256: bd0d0b3b9eb55d3f5541dd261f5426416eff6687365a7536bad946933aadb7a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - einops >=0.6.0
    - pytorch

test:
  imports:
    - local_attention
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lucidrains/local-attention
  summary: Local windowed attention, for language modeling
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
